name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run on manual trigger
  workflow_dispatch:
  # Run on push to main/master
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # =====================================
      # 1. General GitHub Stats
      # =====================================
      - name: General GitHub Stats
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_repositories: yes
          plugin_repositories_featured: IamMichael23/hybrid-rag-framework, IamMichael23/graphrag-vs-lightrag, IamMichael23/golf-chatbot, IamMichael23/crm-integration
          
      # =====================================
      # 2. GitHub Achievements
      # =====================================
      - name: GitHub Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
      # =====================================
      # 3. Most Used Languages
      # =====================================
      - name: Most Used Languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          
      # =====================================
      # 4. Coding Habits
      # =====================================
      - name: Coding Habits
        uses: lowlighter/metrics@latest
        with:
          filename: habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          config_timezone: America/Toronto
          
      # =====================================
      # 5. Isometric Contribution Calendar
      # =====================================
      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
      # =====================================
      # 6. Recent Activity
      # =====================================
      - name: Recent Activity
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
